repos:
  # Keep uv.lock file up to date when pyproject.toml changes
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.14
    hooks:
      - id: uv-lock

  # Lint and format Python code with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter with automatic fixes
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format
